name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - php: '7.4'
            tools: phpunit:9
          - php: '8.0'
            tools: cs2pr,phpcs,phpunit:9,psalm
            analyze: true
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.tools }}

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - run: composer install --no-interaction

      - name: Psalm
        run: psalm --output-format=github
        if: always() && matrix.analyze

      - name: PHP CodeSniffer
        run: phpcs --report=checkstyle | cs2pr
        if: always() && matrix.analyze

      - name: PHPUnit
        run: phpunit --coverage-text
        if: always()